spring:
  application:
    name: ddd-study
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test-ddd
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          batch_size: 50
        order_updates: true
        order_inserts: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true




logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: debug
    org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl: TRACE